In [1]:
import pandas as pd
import numpy as np

data_path_list = [
    "/home/chenzihao/workspace/cc2cc_test5/validate/ccdft_cc-pVDZ_atom-1-1513512_gmtkn-cc-pVDZ.csv",
    "/home/chenzihao/workspace/cc2cc_test5/validate/ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ.csv",
    "/home/chenzihao/workspace/cc2cc_test5/validate/ccdft_cc-pVDZ_atom-1-1428227_gmtkn-cc-pVDZ.csv",
    "/home/chenzihao/workspace/cc2cc_test5/validate/ccdft_cc-pVDZ_atom-1-4149292_gmtkn-cc-pVDZ.csv",
    # "/home/chenzihao/workspace/cc2cc_test5/validate/ccdft_cc-pVDZ_atom-1-1235076_gmtkn-cc-pVDZ.csv",
    # "/home/chenzihao/workspace/cc2cc_test5/validate/ccdft_cc-pVDZ_atom-1-4190857_gmtkn-cc-pVDZ.csv",
    # "/home/chenzihao/workspace/cc2cc_test5/validate/ccdft_cc-pVDZ_atom-1-1256130_gmtkn-cc-pVDZ.csv",
]


for data_path in data_path_list:
    data_record = np.zeros((5, 2))
    stoichiometry_list = np.array(
        [
            [-5, 5, -1, 0, 0],
            [-4, 5, 0, -1, 0],
            [-18, 16, 0, 0, -1],
        ]
    )
    data = pd.read_csv(data_path)
    for i in range(5):
        if len(data) > (i * 100):
            data_scf = data["delta_scf"].to_numpy()[i * 100 : i * 100 + 100]
            delta_dft = data["delta_dft"].to_numpy()[i * 100 : i * 100 + 100]
            data_scf_min = np.min(data_scf)
            data_scf_max = np.max(data_scf)
            data_dft_min = np.min(delta_dft)
            data_dft_max = np.max(delta_dft)
            data_record[i, 0] = np.mean(data_scf)
            data_record[i, 1] = np.mean(delta_dft)
            print(data_scf_max - data_scf_min, data_dft_max - data_dft_min)
        else:
            print("NAN")
    print("")
    print(np.einsum("ij,ki->jk", data_record, stoichiometry_list))

0.08121583445758271 0.0014146486723092266
0.14263314347538447 0.007559250230116277
0.16890390462497296 0.01910394881110733
0.262515880361745 0.05497557172230927
0.6764403611164713 0.27833643801955077

[[ -2.45521601  -5.99671282 -28.01063716]
 [ -2.18310992  -5.20391207 -25.34362561]]
0.046079364355560995 0.0015829934165054738
0.13317122929932546 0.008094859259387022
0.17825737391907914 0.017958430717783358
0.18847052823536536 0.044596395179269166
0.4216860427310465 0.1730526277193576

[[ -2.12148438  -5.7092358  -25.59965654]
 [ -2.18324016  -5.20284752 -25.33746087]]
0.06599549220765089 0.001270188517906945
0.20591668836917632 0.0071569593543472365
0.1256711022887771 0.02013535696528379
0.16796087490566647 0.04358540353553053
0.4697594188966363 0.2077710549016274

[[ -3.87442745  -9.00006956 -42.29049344]
 [ -2.18173192  -5.20049287 -25.3384637 ]]
0.1105475096101665 0.0017149895675174776
0.2406343707395134 0.007690840280645261
0.3269842751978278 0.019464588660014215
0.244700503847102