In [3]:
import numpy as np

data1 = np.load("../data/grids_dft/data_W4_11-o2_cc-pVDZ-benchmark.npz", allow_pickle=True,)
data2 = np.load("../data/grids_dft/data_W4_11-o2_cc-pVDZ.npz", allow_pickle=True,)

In [4]:
data1["grad_cc"]- data2["grad_cc"]

array([[ 1.11963341e-15, -3.89515273e-16,  3.71791486e-12],
       [-1.11963341e-15,  3.89515273e-16, -3.72146758e-12]])

In [10]:
np.random.seed(42)
w_ = np.random.rand(3, 3, 3, 3, 3, 3)
w = w_.copy()
w = w - w.transpose(0, 2, 1, 3, 4, 5)
w = w + w.transpose(0, 2, 1, 3, 5, 4)
print(
    w_
    - w_.transpose(0, 2, 1, 3, 4, 5)
    + w_.transpose(0, 2, 1, 3, 5, 4)
    - w_.transpose(0, 1, 2, 3, 5, 4)
    - w
)

[[[[[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
     [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
     [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]

    [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
     [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
     [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]

    [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
     [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
     [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]]


   [[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
     [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
     [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]

    [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
     [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
     [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]

    [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
     [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
     [ 0.00000000e+00  0.00000000e+00  0.00000000e+00

In [ ]:
# replace string using abcijk with cabkij
def replace(str_, old="abcijk", new="cabkij"):
    return str_.replace(old, new)


print(replace("ijae,kceb"))

ijae,kceb
