In [1]:
import sys

import torch
import numpy as np

sys.path.append("..")
from cc2cc.utils.model.transformer_4_ang import Extractor


device = torch.device("cpu")
model = Extractor().to(device)

PID: 2278557
Is Available: True
GPU: NVIDIA A800-SXM4-80GB
GPU number: None
Current Device: 0
Number of Devices: 8


In [16]:
ANG = 1
RAD = 75

x = torch.rand(ANG, 4, RAD, dtype=torch.float32).to(device)
y = model(x)
print(y.permute(0, 2, 1))

tensor([[[-6.3158e-02, -1.3524e-01, -1.3674e-01, -1.6281e-01],
         [-1.3847e-02, -4.2807e-02, -6.7580e-02,  3.5233e-03],
         [ 1.9700e-01,  1.1547e-01,  9.7578e-02,  1.1453e-01],
         [-1.5845e-01, -1.4112e-01, -9.8887e-02, -1.5928e-01],
         [-3.1107e-02, -5.8836e-02, -7.6085e-02,  1.8269e-02],
         [ 1.9279e-03,  8.4024e-03, -1.0992e-02,  7.9105e-02],
         [ 1.1266e-01,  1.0129e-02,  4.4347e-02,  5.5705e-02],
         [-3.9274e-01, -4.4311e-01, -4.1503e-01, -3.8602e-01],
         [ 2.1509e-01,  2.3901e-01,  2.1464e-01,  2.2310e-01],
         [ 3.2084e-01,  2.9851e-01,  2.8130e-01,  2.6997e-01],
         [-2.8281e-02,  3.5757e-02,  1.1317e-03,  1.0615e-02],
         [-1.6888e-01, -1.5262e-01, -1.4769e-01, -1.3500e-01],
         [-1.5821e-01, -2.0671e-01, -1.5910e-01, -1.9335e-01],
         [-2.7676e-01, -2.6121e-01, -2.4683e-01, -1.9021e-01],
         [-1.8606e-01, -2.2726e-01, -2.6698e-01, -1.9305e-01],
         [ 5.9100e-02,  1.0675e-01,  1.1404e-01,  1.037

In [18]:
indices = np.linspace(0, 74, 75, dtype=int)
# indices[0], indices[1] = 1, 0
# indices = np.random.permutation(indices)

x_swap = x[:, :, indices]
y_swap = model(x_swap)
y_swap_new = torch.zeros_like(y_swap)
y_swap_new[:, :, indices] = y_swap
y_swap = y_swap_new
print(y_swap.permute(0, 2, 1))

tensor([[[-6.3158e-02, -1.3524e-01, -1.3674e-01, -1.6281e-01],
         [-1.3847e-02, -4.2807e-02, -6.7580e-02,  3.5233e-03],
         [ 1.9700e-01,  1.1547e-01,  9.7578e-02,  1.1453e-01],
         [-1.5845e-01, -1.4112e-01, -9.8887e-02, -1.5928e-01],
         [-3.1107e-02, -5.8836e-02, -7.6085e-02,  1.8269e-02],
         [ 1.9279e-03,  8.4024e-03, -1.0992e-02,  7.9105e-02],
         [ 1.1266e-01,  1.0129e-02,  4.4347e-02,  5.5705e-02],
         [-3.9274e-01, -4.4311e-01, -4.1503e-01, -3.8602e-01],
         [ 2.1509e-01,  2.3901e-01,  2.1464e-01,  2.2310e-01],
         [ 3.2084e-01,  2.9851e-01,  2.8130e-01,  2.6997e-01],
         [-2.8281e-02,  3.5757e-02,  1.1317e-03,  1.0615e-02],
         [-1.6888e-01, -1.5262e-01, -1.4769e-01, -1.3500e-01],
         [-1.5821e-01, -2.0671e-01, -1.5910e-01, -1.9335e-01],
         [-2.7676e-01, -2.6121e-01, -2.4683e-01, -1.9021e-01],
         [-1.8606e-01, -2.2726e-01, -2.6698e-01, -1.9305e-01],
         [ 5.9100e-02,  1.0675e-01,  1.1404e-01,  1.037

In [4]:
indices

array([ 4, 63, 10,  0, 35, 61, 28, 12, 69, 64, 34, 42, 49, 18,  9, 22,  5,
       33, 56, 66, 39, 40, 16, 44, 45, 30,  7, 58, 47, 31, 53, 50, 19, 62,
       25, 74, 13, 54,  3, 17, 38,  8, 72,  6, 36, 68, 55, 46, 73, 15, 27,
       41, 26, 48, 24, 43, 67, 57, 11, 32, 70, 59, 65, 37, 29,  1, 52, 21,
        2, 23, 20, 60, 71, 14, 51])

In [1]:
data_json = {
    "molecule0": [
        "al",
        "b",
        "be",
        "c",
        "cl",
        "f",
        "h",
        "n",
        "o",
        "p",
        "s",
        "si",
    ],
    "molecule1": [
        "alh",
        "alh3",
        "bh",
        "bh3",
        "ch",
        "ch2-sing",
        "ch2-trip",
        "ch3",
        "ch4",
        "h2",
        "h2o",
        "h2s",
        "hcl",
        "hf",
        "hs",
        "nh",
        "nh2",
        "nh3",
        "oh",
        "ph3",
        "sih",
        "sih4",
    ],
    "molecule2": [
        "alcl",
        "alf",
        "b2",
        "b2h6",
        "be2",
        "bf",
        "bn",
        "bn3pi",
        "c-hcoh",
        "c-n2h2",
        "c2",
        "c2h2",
        "c2h4",
        "c2h6",
        "cch",
        "cf",
        "ch2c",
        "ch2ch",
        "ch2nh",
        "ch2nh2",
        "ch3f",
        "ch3nh",
        "ch3nh2",
        "cl2",
        "clf",
        "clo",
        "cn",
        "co",
        "cs",
        "f2",
        "h2cn",
        "h2co",
        "hcn",
        "hcnh",
        "hco",
        "hnc",
        "hno",
        "hocl",
        "hof",
        "hoo",
        "hooh",
        "methanol",
        "n2",
        "n2h",
        "n2h4",
        "nh2cl",
        "no",
        "o2",
        "of",
        "p2",
        "s2",
        "si2h6",
        "sif",
        "sih3f",
        "sio",
        "so",
        "ssh",
        "t-hcoh",
        "t-n2h2",
    ],
    "molecule3": [
        "acetaldehyde",
        "allene",
        "becl2",
        "bef2",
        "bhf2",
        "c-hono",
        "c-hooo",
        "c2h3f",
        "c2h5f",
        "ccl2",
        "cf2",
        "ch2f2",
        "cl2o",
        "clcn",
        "cloo",
        "co2",
        "cs2",
        "dioxirane",
        "ethanol",
        "f2o",
        "fo2",
        "formic",
        "hccf",
        "hcno",
        "hcof",
        "hnco",
        "hnnn",
        "hocn",
        "honc",
        "ketene",
        "n2o",
        "no2",
        "o3",
        "oclo",
        "ocs",
        "oxirane",
        "oxirene",
        "propane",
        "propene",
        "propyne",
        "s2o",
        "s3",
        "so2",
        "t-hono",
        "t-hooo",
    ],
    "molecule4": [
        "acetic",
        "alcl3",
        "alf3",
        "bf3",
        "f2co",
        "fccf",
        "foof",
        "glyoxal",
        "nccn",
        "p4",
        "s4-c2v",
        "so3",
    ],
    "molecule5": [
        "cf4",
        "sif4",
    ],
}

In [2]:
data_json_new = {}

for key, value in data_json.items():
    data_json_new[f"{key}-W4_11"] = [f"W4_11-{i_value}" for i_value in value]

In [3]:
data_json_new

{'molecule0-W4_11': ['W4_11-al',
  'W4_11-b',
  'W4_11-be',
  'W4_11-c',
  'W4_11-cl',
  'W4_11-f',
  'W4_11-h',
  'W4_11-n',
  'W4_11-o',
  'W4_11-p',
  'W4_11-s',
  'W4_11-si'],
 'molecule1-W4_11': ['W4_11-alh',
  'W4_11-alh3',
  'W4_11-bh',
  'W4_11-bh3',
  'W4_11-ch',
  'W4_11-ch2-sing',
  'W4_11-ch2-trip',
  'W4_11-ch3',
  'W4_11-ch4',
  'W4_11-h2',
  'W4_11-h2o',
  'W4_11-h2s',
  'W4_11-hcl',
  'W4_11-hf',
  'W4_11-hs',
  'W4_11-nh',
  'W4_11-nh2',
  'W4_11-nh3',
  'W4_11-oh',
  'W4_11-ph3',
  'W4_11-sih',
  'W4_11-sih4'],
 'molecule2-W4_11': ['W4_11-alcl',
  'W4_11-alf',
  'W4_11-b2',
  'W4_11-b2h6',
  'W4_11-be2',
  'W4_11-bf',
  'W4_11-bn',
  'W4_11-bn3pi',
  'W4_11-c-hcoh',
  'W4_11-c-n2h2',
  'W4_11-c2',
  'W4_11-c2h2',
  'W4_11-c2h4',
  'W4_11-c2h6',
  'W4_11-cch',
  'W4_11-cf',
  'W4_11-ch2c',
  'W4_11-ch2ch',
  'W4_11-ch2nh',
  'W4_11-ch2nh2',
  'W4_11-ch3f',
  'W4_11-ch3nh',
  'W4_11-ch3nh2',
  'W4_11-cl2',
  'W4_11-clf',
  'W4_11-clo',
  'W4_11-cn',
  'W4_11-co',
  'W4_