In [1]:
import py3Dmol

from cc2cc.utils import gen_mole

name_mol_list = [
    "AL2X6-alh3",
    "MB16_43-AlH3",
    "W4_11-alh3",
]

for name_mol in name_mol_list:
    # Generate the molecule with the specified parameters
    # The parameters are:
    #       name, stratch_atom, stratch_orientation, stratch_distance and basis set
    mol = gen_mole(
        name_mol,
        0,
        1,
        0,
        "def2-TZVPP",
        True,
        "filtered_gmtkn-def2-TZVPP",
        solve_symmetry=True,
        verbose=0,
    )
    print(f"number of atomic orbitals: {mol.nao}")

    xyz = mol.tostring(format="xyz")

    xyzview = py3Dmol.view()
    xyzview.addModel(xyz, "xyz")
    xyzview.setStyle({"stick": {}, "sphere": {"scale": 0.3}})
    xyzview.setStyle(
        {
            "stick": {},
            "sphere": {"scale": 0.3},
            "label": "atom",
        }
    )
    xyzview.setHoverable(
        {},
        True,
        """function(atom,viewer,event,container) {
            if(!atom.label) {
            atom.label = viewer.addLabel(atom.atom,{position: atom, backgroundColor: 'mintcream', fontColor:'black', fontSize: 18, fontWeight: 'bold', alignment: 'center', showBackground: true, showBorder: true, borderColor: 'black', borderWidth: 1, padding: 2, zIndex: 1000});
            }}""",
        """function(atom,viewer) {
            if(atom.label) {
            viewer.removeLabel(atom.label);
            delete atom.label;
            }
        }""",
        viewer=(0, 0),
    )
    xyzview.zoomTo()
    xyzview.show()

DEBUG True
DEBUG [array(['H', np.float64(0.0), np.float64(0.0), np.float64(1.578518)],
      dtype=object), array(['H', np.float64(-1.367037), np.float64(0.0), np.float64(-0.789259)],
      dtype=object), array(['H', np.float64(1.367037), np.float64(0.0), np.float64(-0.789259)],
      dtype=object), array(['Al', np.float64(0.0), np.float64(0.0), np.float64(0.0)],
      dtype=object)]
DEBUG [ 5.34651205  9.66230003 15.00881208] [[-0.96592588 -0.25881885  0.        ]
 [ 0.          0.          1.        ]
 [ 0.25881885 -0.96592588  0.        ]]
DEBUG [ 5.34651205  9.66230003 15.00881208] [[-0.96592588  0.25881885  0.        ]
 [-0.25881885 -0.96592588  0.        ]
 [ 0.          0.          1.        ]]
DEBUG [ 5.34651205  9.66230003 15.00881208] [[1.00000000e+00 3.08696264e-16 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
number of atomic orbitals: 84


3Dmol.js failed to load for some reason. Please check your browser console for error messages.

DEBUG True
DEBUG [array(['H', np.float64(-0.7926513966411446), np.float64(1.3729124),
       np.float64(0.0)], dtype=object), array(['H', np.float64(-0.7926513966411446), np.float64(-1.3729124),
       np.float64(0.0)], dtype=object), array(['H', np.float64(1.5853027033588554), np.float64(0.0),
       np.float64(0.0)], dtype=object), array(['Al', np.float64(3.35885544289457e-09), np.float64(0.0),
       np.float64(0.0)], dtype=object)]
DEBUG [ 5.39257073  9.74553459 15.13810532] [[-0.96592583  0.25881904  0.        ]
 [-0.25881904 -0.96592583  0.        ]
 [ 0.          0.          1.        ]]
DEBUG [ 5.39257073  9.74553459 15.13810532] [[-0.96592583  0.25881904  0.        ]
 [-0.25881904 -0.96592583  0.        ]
 [ 0.          0.          1.        ]]
DEBUG [ 5.39257073  9.74553459 15.13810532] [[ 1.00000000e+00 -8.25936006e-17  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
number of atomic orbitals: 84


3Dmol.js failed to load for some reason. Please check your browser console for error messages.

DEBUG True
DEBUG [array(['H', np.float64(0.0), np.float64(1.5805), np.float64(0.0)],
      dtype=object), array(['H', np.float64(1.368753), np.float64(-0.79025), np.float64(0.0)],
      dtype=object), array(['H', np.float64(-1.368753), np.float64(-0.79025), np.float64(0.0)],
      dtype=object), array(['Al', np.float64(0.0), np.float64(0.0), np.float64(0.0)],
      dtype=object)]
DEBUG [ 5.35994648  9.68657328 15.04651976] [[-0.9659258   0.25881914  0.        ]
 [-0.25881914 -0.9659258   0.        ]
 [ 0.          0.          1.        ]]
DEBUG [ 5.35994648  9.68657328 15.04651976] [[-0.9659258   0.25881914  0.        ]
 [-0.25881914 -0.9659258   0.        ]
 [ 0.          0.          1.        ]]
DEBUG [ 5.35994648  9.68657328 15.04651976] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
number of atomic orbitals: 84


3Dmol.js failed to load for some reason. Please check your browser console for error messages.

In [ ]:
import numpy as np
data1 = np.load(
    "/home/dhem/workspace/2025.1/data/UPU23-8d_cc-pVDZ_0_1_0.0000_default_cc.npz"
)
data2 = np.load(
    "/home/dhem/workspace/2025.1/data/test_no_grad/UPU23-8d_cc-pVDZ_0_1_0.0000_default_cc.npz"
)

In [ ]:
print(
    data1["cc_dipole"] - data2["cc_dipole"],
    (data1["e_cc"] - data2["e_cc"]) * 627.5094733748099,
)
print(
    data1["dft_dipole"] - data2["dft_dipole"],
    (data1["e_dft"] - data2["e_dft"]) * 627.5094733748099,
)