In [2]:
import py3Dmol

from cc2cc.utils import gen_mole

name_mol_list = [
    "SIE4x4-nh32+_1.0",
    "SIE4x4-nh32+_1.25",
    "SIE4x4-nh32+_1.5",
    "SIE4x4-nh32+_1.75",
]

for name_mol in name_mol_list:
    # Generate the molecule with the specified parameters
    # The parameters are:
    #       name, stratch_atom, stratch_orientation, stratch_distance and basis set
    mol = gen_mole(
        name_mol,
        0,
        1,
        0,
        "def2-TZVPP",
        True,
        "filtered_gmtkn-def2-TZVPP",
        solve_symmetry=True,
        verbose=0,
    )
    print(f"number of atomic orbitals: {mol.nao}")

    xyz = mol.tostring(format="xyz")

    xyzview = py3Dmol.view()
    xyzview.addModel(xyz, "xyz")
    xyzview.setStyle({"stick": {}, "sphere": {"scale": 0.3}})
    xyzview.setStyle(
        {
            "stick": {},
            "sphere": {"scale": 0.3},
            "label": "atom",
        }
    )
    xyzview.setHoverable(
        {},
        True,
        """function(atom,viewer,event,container) {
            if(!atom.label) {
            atom.label = viewer.addLabel(atom.atom,{position: atom, backgroundColor: 'mintcream', fontColor:'black', fontSize: 18, fontWeight: 'bold', alignment: 'center', showBackground: true, showBorder: true, borderColor: 'black', borderWidth: 1, padding: 2, zIndex: 1000});
            }}""",
        """function(atom,viewer) {
            if(atom.label) {
            viewer.removeLabel(atom.label);
            delete atom.label;
            }
        }""",
        viewer=(0, 0),
    )
    xyzview.zoomTo()
    xyzview.show()

DEBUG True
DEBUG [array(['H', np.float64(0.84297303), np.float64(0.48669071),
       np.float64(-1.35892883)], dtype=object), array(['H', np.float64(0.0), np.float64(-0.97338141),
       np.float64(-1.35892883)], dtype=object), array(['H', np.float64(-0.84297303), np.float64(0.48669071),
       np.float64(-1.35892883)], dtype=object), array(['H', np.float64(0.84297303), np.float64(-0.48669071),
       np.float64(1.35892883)], dtype=object), array(['H', np.float64(0.0), np.float64(0.97338141),
       np.float64(1.35892883)], dtype=object), array(['H', np.float64(-0.84297303), np.float64(-0.48669071),
       np.float64(1.35892883)], dtype=object), array(['N', np.float64(0.0), np.float64(0.0), np.float64(-1.08325539)],
      dtype=object), array(['N', np.float64(0.0), np.float64(0.0), np.float64(1.08325539)],
      dtype=object)]
DEBUG [96.96505236 96.96505233 19.94138282] [[ 1.00000000e+00  1.23646075e-08 -7.13651930e-27]
 [ 0.00000000e+00  1.00000000e+00 -1.23777136e-09]
 [ 0.00000000e+

3Dmol.js failed to load for some reason. Please check your browser console for error messages.

DEBUG True
DEBUG [array(['H', np.float64(0.84297303), np.float64(0.48669071),
       np.float64(-1.62974268)], dtype=object), array(['H', np.float64(0.0), np.float64(-0.97338141),
       np.float64(-1.62974268)], dtype=object), array(['H', np.float64(-0.84297303), np.float64(0.48669071),
       np.float64(-1.62974268)], dtype=object), array(['H', np.float64(0.84297303), np.float64(-0.48669071),
       np.float64(1.62974268)], dtype=object), array(['H', np.float64(0.0), np.float64(0.97338141),
       np.float64(1.62974268)], dtype=object), array(['H', np.float64(-0.84297303), np.float64(-0.48669071),
       np.float64(1.62974268)], dtype=object), array(['N', np.float64(0.0), np.float64(0.0), np.float64(-1.35406924)],
      dtype=object), array(['N', np.float64(0.0), np.float64(0.0), np.float64(1.35406924)],
      dtype=object)]
DEBUG [141.07146038 141.07146035  19.94138282] [[ 1.00000000e+00  1.23646027e-08 -3.46061426e-27]
 [ 0.00000000e+00  1.00000000e+00 -9.43919521e-10]
 [ 0.0000000

3Dmol.js failed to load for some reason. Please check your browser console for error messages.

DEBUG True
DEBUG [array(['H', np.float64(-1.90055702), np.float64(-0.84259382),
       np.float64(-0.48734709)], dtype=object), array(['H', np.float64(-1.90055696), np.float64(-0.00075784),
       np.float64(0.97338078)], dtype=object), array(['H', np.float64(-1.90055702), np.float64(0.84335167),
       np.float64(-0.48603446)], dtype=object), array(['H', np.float64(1.90055702), np.float64(-0.84335167),
       np.float64(0.48603446)], dtype=object), array(['H', np.float64(1.90055696), np.float64(0.00075784),
       np.float64(-0.97338078)], dtype=object), array(['H', np.float64(1.90055702), np.float64(0.84259382),
       np.float64(0.48734709)], dtype=object), array(['N', np.float64(-1.624883), np.float64(0.0), np.float64(7e-08)],
      dtype=object), array(['N', np.float64(1.624883), np.float64(0.0), np.float64(-7e-08)],
      dtype=object)]
DEBUG [ 19.94138045 194.28096752 194.28096846] [[-1.00000000e+00  7.29755609e-10  3.44833036e-08]
 [ 7.66638457e-10 -9.99058869e-01  4.33747952e-

3Dmol.js failed to load for some reason. Please check your browser console for error messages.

DEBUG True
DEBUG [array(['H', np.float64(0.84297303), np.float64(0.48669071),
       np.float64(-2.17137038)], dtype=object), array(['H', np.float64(0.0), np.float64(-0.97338141),
       np.float64(-2.17137038)], dtype=object), array(['H', np.float64(-0.84297303), np.float64(0.48669071),
       np.float64(-2.17137038)], dtype=object), array(['H', np.float64(0.84297303), np.float64(-0.48669071),
       np.float64(2.17137038)], dtype=object), array(['H', np.float64(0.0), np.float64(0.97338141),
       np.float64(2.17137038)], dtype=object), array(['H', np.float64(-0.84297303), np.float64(-0.48669071),
       np.float64(2.17137038)], dtype=object), array(['N', np.float64(0.0), np.float64(0.0), np.float64(-1.89569694)],
      dtype=object), array(['N', np.float64(0.0), np.float64(0.0), np.float64(1.89569694)],
      dtype=object)]
DEBUG [256.59350198 256.59350194  19.94138282] [[ 1.00000000e+00  1.23646222e-08 -1.20795640e-27]
 [ 0.00000000e+00  1.00000000e+00 -6.43711748e-10]
 [ 0.0000000

3Dmol.js failed to load for some reason. Please check your browser console for error messages.

In [ ]:
import numpy as np
data1 = np.load(
    "/home/dhem/workspace/2025.1/data/UPU23-8d_cc-pVDZ_0_1_0.0000_default_cc.npz"
)
data2 = np.load(
    "/home/dhem/workspace/2025.1/data/test_no_grad/UPU23-8d_cc-pVDZ_0_1_0.0000_default_cc.npz"
)

In [ ]:
print(
    data1["cc_dipole"] - data2["cc_dipole"],
    (data1["e_cc"] - data2["e_cc"]) * 627.5094733748099,
)
print(
    data1["dft_dipole"] - data2["dft_dipole"],
    (data1["e_dft"] - data2["e_dft"]) * 627.5094733748099,
)