In [7]:
import py3Dmol

from cc2cc.utils import gen_mole

name_mol_list = [
    "AHB21-10A",
    "AHB21-15A",
]

for name_mol in name_mol_list:
    # Generate the molecule with the specified parameters
    # The parameters are:
    #       name, stratch_atom, stratch_orientation, stratch_distance and basis set
    mol = gen_mole(
        name_mol,
        0,
        1,
        0,
        "def2-TZVPP",
        True,
        "filtered_gmtkn-def2-TZVPP",
        if_rotate=True,
        if_rotate_random=False,
        solve_symmetry=True,
        verbose=0,
    )
    print(f"number of atomic orbitals: {mol.nao}")

    xyz = mol.tostring(format="xyz")
    print(xyz)

    xyzview = py3Dmol.view()
    xyzview.addModel(xyz, "xyz")
    xyzview.setStyle({"stick": {}, "sphere": {"scale": 0.3}})
    xyzview.setStyle(
        {
            "stick": {},
            "sphere": {"scale": 0.3},
            "label": "atom",
        }
    )
    xyzview.setHoverable(
        {},
        True,
        """function(atom,viewer,event,container) {
            if(!atom.label) {
            atom.label = viewer.addLabel(atom.atom,{position: atom, backgroundColor: 'mintcream', fontColor:'black', fontSize: 18, fontWeight: 'bold', alignment: 'center', showBackground: true, showBorder: true, borderColor: 'black', borderWidth: 1, padding: 2, zIndex: 1000});
            }}""",
        """function(atom,viewer) {
            if(atom.label) {
            viewer.removeLabel(atom.label);
            delete atom.label;
            }
        }""",
        viewer=(0, 0),
    )
    xyzview.zoomTo()
    xyzview.show()

DEBUG True
DEBUG [array(['H', np.float64(0.293251706622651), np.float64(0.6243724957134614),
       np.float64(0.5878214859642632)], dtype=object), array(['O', np.float64(-0.018472343377349043),
       np.float64(-0.03933011428653856),
       np.float64(-0.037027714035736875)], dtype=object)]
DEBUG [8.83202309e-01 1.38777878e-17 8.83202309e-01] [[ 0.94620361 -0.32357182  0.        ]
 [-0.2355917  -0.68892811 -0.68547401]
 [-0.22180007 -0.64859798  0.7280971 ]]
DEBUG [ 8.83202309e-01 -2.77555756e-17  8.83202309e-01] [[ 9.46203614e-01 -3.23571816e-01  4.32970040e-17]
 [-3.23571816e-01 -9.46203614e-01 -1.88352395e-17]
 [-1.30368011e-18 -3.81228144e-18  1.00000000e+00]]
DEBUG [4.46059258e-31 8.83202309e-01 8.83202309e-01] [[ 1.00000000e+00  6.21490732e-17 -4.38702168e-18]
 [ 0.00000000e+00 -9.95879757e-01  1.60755207e-01]
 [ 0.00000000e+00  9.06835690e-02  9.86994308e-01]]
number of atomic orbitals: 45
2
XYZ from PySCF
H           0.90629558        0.00000000       -0.00000000
O          -

3Dmol.js failed to load for some reason. Please check your browser console for error messages.

DEBUG True
DEBUG [array(['H', np.float64(-0.9330393664371378),
       np.float64(0.5007346326344921), np.float64(-0.7550293380317871)],
      dtype=object), array(['S', np.float64(0.02932378356286225),
       np.float64(-0.015737207365507766),
       np.float64(0.023729241968213022)], dtype=object)]
DEBUG [-2.22044605e-16  1.75984519e+00  1.75984519e+00] [[-0.71743251  0.69662802  0.        ]
 [ 0.38502481  0.3965234   0.83338172]
 [-0.58055706 -0.59789514  0.55269785]]
DEBUG [-1.11022302e-16  1.75984519e+00  1.75984519e+00] [[-7.17432506e-01  6.96628021e-01 -1.73321087e-15]
 [ 6.96628021e-01  7.17432506e-01 -1.62777926e-15]
 [-1.09505167e-16 -1.12775490e-16  1.00000000e+00]]
DEBUG [1.92596569e-30 1.75984519e+00 1.75984519e+00] [[ 1.00000000e+00 -8.32092977e-17  0.00000000e+00]
 [ 0.00000000e+00 -6.42516069e-01  7.66272211e-01]
 [ 0.00000000e+00  7.66272211e-01  6.42516069e-01]]
number of atomic orbitals: 56
2
XYZ from PySCF
H           1.30052564        0.00000000        0.00000000
S 

3Dmol.js failed to load for some reason. Please check your browser console for error messages.

In [ ]:
# import numpy as np
# data1 = np.load(
#     "/home/dhem/workspace/2025.1/data/UPU23-8d_cc-pVDZ_0_1_0.0000_default_cc.npz"
# )
# data2 = np.load(
#     "/home/dhem/workspace/2025.1/data/test_no_grad/UPU23-8d_cc-pVDZ_0_1_0.0000_default_cc.npz"
# )

In [ ]:
# print(
#     data1["cc_dipole"] - data2["cc_dipole"],
#     (data1["e_cc"] - data2["e_cc"]) * 627.5094733748099,
# )
# print(
#     data1["dft_dipole"] - data2["dft_dipole"],
#     (data1["e_dft"] - data2["e_dft"]) * 627.5094733748099,
# )

In [5]:
import numpy as np
np.sqrt(0.004**2*3)

np.float64(0.0069282032302755096)